version: '3'
services:
  krakend:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/:/etc/krakend
      - ./config/plugins/:/opt/krakend/plugin
    ports:
      - "3890:3890"    
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:      
      - bill-manager
      - api-backend-test
      # - jaeger
      # - jaeger-ui
    networks:
      - host      

  api-backend-test:
    image: docker.io/library/api-backend-test 
    ports:
      - "8000:8000"
    networks:
      - host

  bill-manager:
    image: docker.io/library/bill-manager
    ports:
      - "8001:8001"
    networks:
      - host
      
  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "3335:16686" # Jaeger UI
  #     - "6831:6831"   # Agent UDP Thrift
  #     - 14268:14268 # http
  #   environment:
  #     - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  # jaeger-ui:
  #   image: jaegertracing/all-in-one
  #   ports:
  #     - "16686:16686"
  #   environment:
  #     - COLLECTOR_ZIPKIN_HTTP_PORT=9411
networks:
  host:
    # name: host
    # external: true