start:
	docker compose up

ex1:
	cat ./config/krakend/krakend-01.json > ./config/krakend/krakend.json

ex2:
	cat ./config/krakend/krakend-02.json > ./config/krakend/krakend.json

ex3:
	cat ./config/krakend/krakend-03.json > ./config/krakend/krakend.json

ex4:
	cat ./config/krakend/krakend-04.json > ./config/krakend/krakend.json

ex5:
	cat ./config/krakend/krakend-05.json > ./config/krakend/krakend.json

ex6:
	cat ./config/krakend/krakend-06.json > ./config/krakend/krakend.json

ex7:
	cat ./config/krakend/krakend-07.json > ./config/krakend/krakend.json

ex8:
	cat ./config/krakend/krakend-08-plugin.json > ./config/krakend/krakend.json