start:
	docker compose up

ex1:
	cat ./config/krakend-01.json > ./config/krakend.json

ex2:
	cat ./config/krakend-02.json > ./config/krakend.json

ex3:
	cat ./config/krakend-03.json > ./config/krakend.json

ex4:
	cat ./config/krakend-04.json > ./config/krakend.json

ex5:
	cat ./config/krakend-05.json > ./config/krakend.json

ex6:
	cat ./config/krakend-06.json > ./config/krakend.json

ex7:
	cat ./config/krakend-07.json > ./config/krakend.json